site_name: AtlasCore
site_description: Plataforma backend para entrevista com FastAPI, DDD, Clean Architecture, Postgres, Redis, Kafka e MkDocs.
site_author: Matheus Paiva

docs_dir: docs/pt-br
site_dir: site/pt-br

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: blue

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Guia do Repositório:
      - Mapa do Projeto: repositorio/mapa-do-projeto.md
      - Anatomia de uma API: repositorio/anatomia-api.md
      - Anatomia de Módulo: repositorio/anatomia-modulo.md
  - Arquitetura:
      - Visão Arquitetural: arquitetura/visao-geral.md
      - Catálogo de Serviços: arquitetura/catalogo-servicos.md
      - Fronteiras: arquitetura/fronteiras.md
  - Serviços:
      - Auth API: servicos/auth-api.md
      - Core API: servicos/core-api.md
      - Eventing API: servicos/eventing-api.md
      - Notification API: servicos/notification-api.md
      - Observability API: servicos/observability-api.md
      - Worker: servicos/worker.md
  - Domínio Exemplo:
      - Livraria: dominios/livraria.md
      - Public Assets: dominios/public-assets.md
  - Infraestrutura: infraestrutura.md
  - Testes e Workflow: testes-workflow.md
  - Guia de Entrevista: guia-entrevista.md
