FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/apps/core_api/src:/app/packages/shared_kernel/src

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false
RUN poetry install --no-root

COPY apps/core_api/src ./apps/core_api/src
COPY apps/core_api/alembic.ini ./apps/core_api/alembic.ini
COPY apps/core_api/alembic ./apps/core_api/alembic
COPY packages ./packages

EXPOSE 8002

CMD ["uvicorn", "core_api.main:app", "--host", "0.0.0.0", "--port", "8002"]
